"""Independent verification of the Phase 2 groups and automaton (implementation B).

This module shares no code path with the primary construction:
* A₅ is generated by closure from two generators using pure-Python tuple
  composition, rather than enumerated and filtered, and parity comes from the
  cycle decomposition rather than inversion counting;
* its Cayley table is built by dictionary lookup, not a vectorised key search;
* group axioms and structure (solvability, element orders, conjugacy classes)
  are checked from the table alone;
* F^T is evaluated from its symbolic word expansion (2^T letters), not by
  iterating F.
"""

from collections import Counter
from typing import Dict, Iterable, List, Set, Tuple

import numpy as np

from phase2.automaton import iterate
from phase2.groups import a5_permutations, get_group

Perm = Tuple[int, ...]

# (0 1 2) and (0 1 2 3 4): a 3-cycle and a 5-cycle generate A₅.
A5_GENERATORS: Tuple[Perm, Perm] = ((1, 2, 0, 3, 4), (1, 2, 3, 4, 0))


# ============================================================================
# Implementation B of A₅
# ============================================================================


def compose(p: Perm, q: Perm) -> Perm:
    """(p · q)(x) = p(q(x))."""
    return tuple(p[q[x]] for x in range(len(q)))


def parity_from_cycles(perm: Perm) -> int:
    """0 for even, 1 for odd: a k-cycle is k-1 transpositions."""
    seen: Set[int] = set()
    transpositions = 0
    for start in range(len(perm)):
        length, x = 0, start
        while x not in seen:
            seen.add(x)
            x = perm[x]
            length += 1
        transpositions += max(length - 1, 0)
    return transpositions % 2


def generate_by_closure(generators: Iterable[Perm]) -> List[Perm]:
    generators = list(generators)
    identity = tuple(range(len(generators[0])))
    elements = {identity}
    frontier = [identity]
    while frontier:
        new = []
        for element in frontier:
            for generator in generators:
                product = compose(element, generator)
                if product not in elements:
                    elements.add(product)
                    new.append(product)
        frontier = new
    return sorted(elements)


def cayley_table_from_elements(elements: List[Perm]) -> np.ndarray:
    index = {element: i for i, element in enumerate(elements)}
    rows = []
    for a in elements:
        row = []
        for b in elements:
            product = compose(a, b)
            if product not in index:
                raise ValueError(f"element set is not closed: {a}·{b} = {product}")
            row.append(index[product])
        rows.append(row)
    return np.array(rows, dtype=np.int64)


# ============================================================================
# Structural checks from a Cayley table
# ============================================================================


def check_group_axioms(table: np.ndarray) -> Dict[str, bool]:
    t = np.asarray(table)
    m = t.shape[0]
    closure = t.ndim == 2 and t.shape == (m, m) and t.min() >= 0 and t.max() < m
    if not closure:
        return {"closure": False, "associativity": False, "identity": False, "inverses": False}

    ids = np.arange(m)
    left = t[t[:, :, None], ids[None, None, :]]  # (a·b)·c
    right = t[ids[:, None, None], t[None, :, :]]  # a·(b·c)
    associativity = bool(np.array_equal(left, right))

    identities = [e for e in range(m) if np.array_equal(t[e], ids) and np.array_equal(t[:, e], ids)]
    identity = len(identities) == 1
    inverses = False
    if identity:
        e = identities[0]
        has_right = (t == e).sum(axis=1) == 1
        inv = (t == e).argmax(axis=1)
        inverses = bool(has_right.all() and (t[inv, ids] == e).all())
    return {"closure": True, "associativity": associativity, "identity": identity, "inverses": inverses}


def identity_of(table: np.ndarray) -> int:
    ids = np.arange(table.shape[0])
    return next(e for e in range(table.shape[0]) if np.array_equal(table[e], ids))


def is_abelian(table: np.ndarray) -> bool:
    return bool(np.array_equal(table, table.T))


def generated_subgroup(table: np.ndarray, generators: Iterable[int]) -> Set[int]:
    elements = {identity_of(table), *(int(g) for g in generators)}
    while True:
        products = {int(table[a, b]) for a in elements for b in elements}
        if products <= elements:
            return elements
        elements |= products


def derived_series(table: np.ndarray) -> Tuple[bool, List[int]]:
    """(is_solvable, orders of G ⊇ G' ⊇ G'' ⊇ …)."""
    e = identity_of(table)
    inv = (table == e).argmax(axis=1)
    current = set(range(table.shape[0]))
    orders = [len(current)]
    while True:
        commutators = {int(table[table[inv[a], inv[b]], table[a, b]]) for a in current for b in current}
        nxt = generated_subgroup(table, commutators)
        orders.append(len(nxt))
        if len(nxt) == 1:
            return True, orders
        if len(nxt) == len(current):
            return False, orders
        current = nxt


def element_order_counts(table: np.ndarray) -> Dict[int, int]:
    e = identity_of(table)
    counts: Counter = Counter()
    for a in range(table.shape[0]):
        power, k = a, 1
        while power != e:
            power = int(table[power, a])
            k += 1
        counts[k] += 1
    return dict(sorted(counts.items()))


def conjugacy_class_sizes(table: np.ndarray) -> List[int]:
    e = identity_of(table)
    inv = (table == e).argmax(axis=1)
    remaining = set(range(table.shape[0]))
    sizes = []
    while remaining:
        a = next(iter(remaining))
        conjugacy_class = {int(table[table[g, a], inv[g]]) for g in range(table.shape[0])}
        sizes.append(len(conjugacy_class))
        remaining -= conjugacy_class
    return sorted(sizes)


# ============================================================================
# Group verification reports
# ============================================================================


def verify_a5() -> Dict:
    primary = get_group("A5")
    elements = generate_by_closure(A5_GENERATORS)
    table_b = cayley_table_from_elements(elements)
    solvable, series = derived_series(table_b)
    checks = {
        "order_60": len(elements) == 60 and primary.order == 60,
        "closure_elements_all_even": all(parity_from_cycles(p) == 0 for p in elements),
        "same_lexicographic_labelling": [tuple(p) for p in a5_permutations().tolist()] == elements,
        "primary_table_equals_independent_table": bool(np.array_equal(primary.table, table_b)),
        **{f"axiom_{name}": ok for name, ok in check_group_axioms(table_b).items()},
        "identity_is_id_0": identity_of(table_b) == 0 == primary.identity,
        "primary_inverses_correct": bool((table_b[np.arange(60), primary.inverse] == 0).all()),
        "non_abelian": not is_abelian(table_b),
        "non_solvable_perfect": (not solvable) and series[:2] == [60, 60],
        "element_orders_1:1_2:15_3:20_5:24": element_order_counts(table_b) == {1: 1, 2: 15, 3: 20, 5: 24},
        "conjugacy_classes_1_12_12_15_20": conjugacy_class_sizes(table_b) == [1, 12, 12, 15, 20],
    }
    return {"group": "A5", "derived_series_orders": series, "checks": checks, "passed": all(checks.values())}


def verify_cyclic(order: int) -> Dict:
    primary = get_group(f"Z{order}")
    table_b = np.array([[(a + b) % order for b in range(order)] for a in range(order)], dtype=np.int64)
    solvable, series = derived_series(table_b)
    orders = element_order_counts(table_b)
    checks = {
        f"order_{order}": primary.order == order,
        "primary_table_equals_independent_table": bool(np.array_equal(primary.table, table_b)),
        **{f"axiom_{name}": ok for name, ok in check_group_axioms(table_b).items()},
        "abelian": is_abelian(table_b),
        "solvable": solvable,
        "cyclic_has_generator": orders.get(order, 0) > 0,
    }
    return {"group": f"Z{order}", "derived_series_orders": series, "checks": checks, "passed": all(checks.values())}


# ============================================================================
# F^T against its symbolic word expansion
# ============================================================================


def symbolic_word(steps: int) -> List[int]:
    """Cell offsets j (meaning s[i+j]) whose left-to-right product is F^steps(s)[i].

    F(s)[i] = s[i]·s[i+1], so the word for step t+1 is word_t followed by
    word_t shifted by one cell.
    """
    word = [0]
    for _ in range(steps):
        word = word + [j + 1 for j in word]
    return word


def word_run_count(word: List[int]) -> int:
    return 1 + sum(1 for a, b in zip(word, word[1:]) if a != b)


def expected_run_count(steps: int) -> int:
    return {0: 1, 1: 2}.get(steps, 3 * 2 ** (steps - 2) if steps >= 2 else 0)


def evaluate_word(table: np.ndarray, states: np.ndarray, word: List[int]) -> np.ndarray:
    n = states.shape[-1]
    positions = np.arange(n)
    result = states[:, (positions + word[0]) % n]
    for offset in word[1:]:
        result = table[result, states[:, (positions + offset) % n]]
    return result


def verify_word_expansion(group_name: str, independent_table: np.ndarray, t_max: int = 8, n: int = 17,
                          num_states: int = 256, seed: int = 0) -> Dict:
    group = get_group(group_name)
    states = np.random.default_rng(seed).integers(0, group.order, size=(num_states, n))
    per_t = {}
    for t in range(t_max + 1):
        word = symbolic_word(t)
        per_t[t] = {
            "letters": len(word),
            "runs": word_run_count(word),
            "runs_match_3x2^(T-2)": word_run_count(word) == expected_run_count(t),
            "iteration_equals_word": bool(np.array_equal(iterate(group, states, t), evaluate_word(independent_table, states, word))),
        }
    passed = all(r["runs_match_3x2^(T-2)"] and r["iteration_equals_word"] for r in per_t.values())
    return {"group": group_name, "n": n, "num_states": num_states, "per_T": per_t, "passed": passed}


# ============================================================================
# Control tasks and the Z60 shortcut
# ============================================================================


def reference_targets(table: np.ndarray, task: str, state: List[int], t: int) -> List[int]:
    """Pure-Python, cell-by-cell targets (no numpy indexing, no iterate())."""
    n = len(state)
    if task == "c1_span":
        return [int(table[state[i]][state[(i + t) % n]]) for i in range(n)]
    if task == "c2_word":
        out = []
        for i in range(n):
            product = state[i]
            for j in range(1, t + 1):
                product = int(table[product][state[(i + j) % n]])
            out.append(product)
        return out
    if task == "main":
        current = list(state)
        for _ in range(t):
            current = [int(table[current[i]][current[(i + 1) % n]]) for i in range(n)]
        return current
    raise ValueError(task)


def verify_tasks(group_name: str, independent_table: np.ndarray, t_values=(1, 2, 4, 8), n: int = 17,
                 num_states: int = 64, seed: int = 1) -> Dict:
    from phase2.tasks import TASKS, make_targets

    group = get_group(group_name)
    states = np.random.default_rng(seed).integers(0, group.order, size=(num_states, n))
    table_list = independent_table.tolist()
    results = {}
    for task in TASKS:
        for t in t_values:
            produced = make_targets(group, task, states, t).tolist()
            expected = [reference_targets(table_list, task, row, t) for row in states.tolist()]
            results[f"{task}/T{t}"] = produced == expected
    t1_identical = all(
        np.array_equal(make_targets(group, "main", states, 1), make_targets(group, task, states, 1)) for task in TASKS
    )
    return {"group": group_name, "per_task": results, "tasks_identical_at_T1": t1_identical,
            "passed": all(results.values()) and t1_identical}


def z60_closed_form(states: np.ndarray, t: int) -> np.ndarray:
    """F^T for Z60 in closed form: Σ_j C(T, j) · s[i+j] mod 60 (abelian shortcut)."""
    from math import comb

    result = np.zeros_like(states)
    for j in range(t + 1):
        result = (result + comb(t, j) * np.roll(states, -j, axis=-1)) % 60
    return result


def verify_z60_closed_form(t_values=(1, 2, 4, 8), n: int = 17, num_states: int = 256, seed: int = 2) -> Dict:
    states = np.random.default_rng(seed).integers(0, 60, size=(num_states, n))
    per_t = {t: bool(np.array_equal(iterate(get_group("Z60"), states, t), z60_closed_form(states, t))) for t in t_values}
    return {"group": "Z60", "closed_form_equals_iteration": per_t, "passed": all(per_t.values())}


def run_verification(t_max: int = 8, n: int = 17) -> Dict:
    a5 = verify_a5()
    z60 = verify_cyclic(60)
    a5_table_b = cayley_table_from_elements(generate_by_closure(A5_GENERATORS))
    z60_table_b = np.array([[(a + b) % 60 for b in range(60)] for a in range(60)], dtype=np.int64)
    words = {
        "A5": verify_word_expansion("A5", a5_table_b, t_max=t_max, n=n),
        "Z60": verify_word_expansion("Z60", z60_table_b, t_max=t_max, n=n),
    }
    tasks = {"A5": verify_tasks("A5", a5_table_b, n=n), "Z60": verify_tasks("Z60", z60_table_b, n=n)}
    closed_form = verify_z60_closed_form(n=n)
    passed = (a5["passed"] and z60["passed"] and all(w["passed"] for w in words.values())
              and all(t["passed"] for t in tasks.values()) and closed_form["passed"])
    return {
        "A5": a5,
        "Z60": z60,
        "word_expansion": words,
        "tasks": tasks,
        "z60_closed_form_shortcut": closed_form,
        "passed": passed,
    }
